trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - script: |
        # Add script to build PEGA application here
        ./path/to/build_script.sh
        echo "Building PEGA application"

- stage: Test
  displayName: Run Tests
  jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    - script: |
        # Add script to run tests here
        echo "Running tests"
    - script: echo "Tests completed"

- stage: InvokeAPI
  displayName: Invoke PEGA REST API
  jobs:
  - job: InvokeAPIJob
    displayName: Invoke API Job
    steps:
    - script: |
        - script: |
              # Bash script to invoke REST API
              # Replace <API_ENDPOINT> with the actual API endpoint
              # Making a GET request
              curl -X GET <API_ENDPOINT>

              # Making a POST request with JSON payload
              curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' <API_ENDPOINT>
        echo "Invoking PEGA REST API"
