trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - script: |
        # Add script to build PEGA application here
        ./path/to/build_script.sh
        echo "Building PEGA application"

- stage: Test
  displayName: Run Tests
  jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    - script: |
        # Add script to run tests here
        echo "Running tests"
    - script: echo "Tests completed"
pool:
  vmImage: 'ubuntu-latest'

variables:
  apiEndpoint: 'https://sandhata01.pegalabs.io/prweb'
  apiKey: $(API_KEY)  # Replace with your API key variable

steps:
- script: |
    # Set the API endpoint and key as environment variables
    echo "##vso[task.setvariable variable=API_ENDPOINT]$(apiEndpoint)"
    echo "##vso[task.setvariable variable=API_KEY]$(apiKey)"

    # Install necessary dependencies (if any)
    # e.g., npm install, pip install, etc.

    # Call the API using cURL or any other appropriate tool
    curl -X GET -H "Authorization: $(API_KEY)" $(API_ENDPOINT)/your/api/endpoint
  displayName: 'Invoke API'