trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - script: |
        # Add script to build PEGA application here
        ./path/to/build_script.sh
        echo "Building PEGA application"

- stage: Test
  displayName: Run Tests
  jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    - script: |
        # Add script to run tests here
        echo "Running tests"
    - script: echo "Tests completed"
